services:
  apache2:
    build:
      context: ../../..
      dockerfile: ./infra/docker/prod/apache2/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - laravel_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  laravel_db_data:
    driver: local